//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeReimbursement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeReimbursementEntities1 : DbContext
    {
        public EmployeeReimbursementEntities1()
            : base("name=EmployeeReimbursementEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblApprovalLevelMaster> tblApprovalLevelMasters { get; set; }
        public virtual DbSet<tblClaimMaster> tblClaimMasters { get; set; }
        public virtual DbSet<tblClaimTransaction> tblClaimTransactions { get; set; }
        public virtual DbSet<tblClaimWorkFlow> tblClaimWorkFlows { get; set; }
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
    }
}
