//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeReimbursement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaimMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClaimMaster()
        {
            this.tblClaimApprovalDetails = new HashSet<tblClaimApprovalDetail>();
            this.tblClaimTransactions = new HashSet<tblClaimTransaction>();
        }
    
        public int ClaimID { get; set; }
        public string Description { get; set; }
        public string RequestType { get; set; }
        public string UserID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimApprovalDetail> tblClaimApprovalDetails { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimTransaction> tblClaimTransactions { get; set; }
    }
}
