//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeReimbursement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaimApprovalDetail
    {
        public int ClaimID { get; set; }
        public int ApproverID { get; set; }
        public string ApproverComment { get; set; }
        public string ApproverType { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual tblClaimMaster tblClaimMaster { get; set; }
    }
}
