//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeReimbursement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaimTransaction
    {
        public int TransactionId { get; set; }
        public Nullable<int> Claimid { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApprovalLevelId { get; set; }
        public string FileUpload { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
