//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeReimbursement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblUser
    {

        [Required]
        public int UserId { get; set; }

        [Required]
        [DisplayName("First Name")]

        public string FirstName { get; set; }

        [Required]
        [DisplayName("Middle Name")]
        public string MiddleName { get; set; }

        [Required]
        [DisplayName("Last Name")]

        public string LastName { get; set; }

        [Required]

        public string Gender { get; set; }

        [Required]
        [DisplayName("Password")]

        public string PasswordHash { get; set; }

        [Required]
        [DisplayName("Department")]

        public Nullable<int> DepartmentId { get; set; }

        [Required]
        [DisplayName("Designation")]

        public Nullable<int> DesignationId { get; set; }

        [Required]
        [DisplayName("Reporting Manager")]

        public string ReportingManager { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}
